import { ApiProperty } from '@nestjs/swagger';

export interface Citation {
  sourcePath: string;
  content: string;
  score: number;
}

export class ChatResponseDto {
  @ApiProperty({
    description: 'The answer generated by the agent',
    example: 'To reset your password, go to the login page and click "Forgot Password".',
  })
  answer: string;

  @ApiProperty({
    description: 'Citations from the knowledge base used to generate the answer',
    type: 'array',
    items: {
      type: 'object',
      properties: {
        sourcePath: { type: 'string', example: '/knowledge/support/password-reset.pdf' },
        content: { type: 'string', example: 'Password reset instructions...' },
        score: { type: 'number', example: 0.92 },
      },
    },
  })
  citations: Citation[];

  @ApiProperty({
    description: 'The LLM provider used to generate the response',
    example: 'gpt-4o',
    enum: ['gpt-4o', 'claude-3.5-sonnet', 'ollama'],
  })
  modelUsed: string;

  @ApiProperty({
    description: 'The session ID for conversation continuity',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  sessionId: string;
}
